/**
 * main.rs
 *
 * Provided a schema.rs file generated by diesel, further generate boilerplate code.
 * The schema is parsed into a struct(found in parser.rs)
 * which is then used to fill in a given template file
**/
use diesel_schema_parser::{generator, parser, utils};

use serde_json::Value;

fn main() {
    let config_string = utils::open_file("./.db-schema-parser-config.json");

    let config: Value = serde_json::from_str(&config_string).expect("Error parsing json config!");

    let schema_path = config["schema"].as_str().unwrap();
    let template_path = config["template"].as_str().unwrap();
    let models_path = config["models"].as_str().unwrap();

    let schema_string = utils::open_file(schema_path);
    let template_string = utils::open_file(template_path);

    let schema = parser::parse_schema(&schema_string).expect("Error parsing your schema!");

    println!("Generating {} models", schema.len());

    let count = generator::generate_models(&template_string, &schema, models_path)
        .expect("Error generating models!");

    println!("Generated {} models", count);
}
